/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.1742)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [PatientDemographics]    Script Date: 12/13/2018 20:02:50 ******/
CREATE DATABASE [PatientDemographics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatientDemographics', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PatientDemographics.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PatientDemographics_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PatientDemographics_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PatientDemographics] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PatientDemographics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PatientDemographics] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PatientDemographics] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PatientDemographics] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PatientDemographics] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PatientDemographics] SET ARITHABORT OFF 
GO

ALTER DATABASE [PatientDemographics] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PatientDemographics] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PatientDemographics] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PatientDemographics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PatientDemographics] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PatientDemographics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PatientDemographics] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PatientDemographics] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PatientDemographics] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PatientDemographics] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PatientDemographics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PatientDemographics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PatientDemographics] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PatientDemographics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PatientDemographics] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PatientDemographics] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PatientDemographics] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PatientDemographics] SET RECOVERY FULL 
GO

ALTER DATABASE [PatientDemographics] SET  MULTI_USER 
GO

ALTER DATABASE [PatientDemographics] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PatientDemographics] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PatientDemographics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PatientDemographics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PatientDemographics] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PatientDemographics] SET QUERY_STORE = OFF
GO

USE [PatientDemographics]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PatientDemographics] SET  READ_WRITE 
GO


